%YAML:1.0
---
################### System ###################
start_time: 1642661813.788321 
# start_time: 1642661813.731114721

# R0: !!opencv-matrix
#    rows: 3
#    cols: 3
#    dt: d
#    data: [0.7596589577663048, 0.33014506555777096, 0.5602878756257943, 
#          -0.3425403807000381, 0.9354850015432803, -0.08679803844235526, 
#          -0.5527968482863151, -0.1259843147991957, 0.8237375777207767]
         
# V0: !!opencv-matrix
#    rows: 3
#    cols: 1
#    dt: d
#    data: [0.0, 0.0, 0.0]

# t0: !!opencv-matrix
#    rows: 3
#    cols: 1
#    dt: d
#    data: [0.24429327236400367, 0.48309069662719045, 0.08810322384290041]

R0: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [0.7938649 ,  0.31754079,  0.51860042,
         -0.33633739,  0.93979121, -0.06057756, 
         -0.50661193, -0.12633435,  0.85286806]
         
V0: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [0.0, 0.0, 0.0]

t0: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [0.22483599, 0.49789479, 0.05495352]

cloud_path: "/home/yuanicg/code/CANNY_EVIT/cloud/Robot.txt"
result_path: "/home/yuanicg/data/EVIT/result/robot_fast_result/"
timeSurface_decay_factor: 30.0e-3 
timeSurface_truncate_threshold: 100.0

# timeSurface_decay_factor: 30.0e-3 
imu_num_for_frame: 7
window_size: 6

frame_num_for_init: 5
imu_num_for_init_frame: 5
init_freq: 300 # hz

min_num_events_for_frame: 70000
min_num_imu_for_frame: 6

################### Event Camera ###################
height: 480
width: 640
distortion_model: "plumb_bob" # equidistant
K: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 327.32749,    0.     ,  304.97749,
         0.     ,  327.46184,  235.37621,
         0.     ,    0.     ,    1.     ]
distortion: !!opencv-matrix
   rows: 5
   cols: 1
   dt: d
   data: [-0.031982, 0.041966, -0.000507, -0.001031, 0.000000]

P: !!opencv-matrix
   rows: 3
   cols: 4
   dt: d
   data: [ 339.69174,    0.     ,  305.8753 ,    0.     ,
            0.     ,  340.96127,  235.33929,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]

Rbc: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [0.01120354,  0.0218441 ,  0.99969861,
         -0.99976045, -0.01855423,  0.01160966,  
          0.01880224, -0.9995892 ,  0.021631]
tbc: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [0.12907465,  0.07967281, 0.025]

# Rbc: !!opencv-matrix
#    rows: 3
#    cols: 3
#    dt: d 
#    data: [ 0., 0., 1.,
#          -1., 0., 0.,
#          0., -1., 0.]

# tbc: !!opencv-matrix
#    rows: 3
#    cols: 1
#    dt: d
#    data: [ 0.10308037, 0.0825, 0.025]



################### imu parameter ###################
acc_n: 0.12655720309610252         # accelerometer measurement noise standard deviation.
gyr_n: 0.07294729852113113         # gyroscope measurement noise standard deviation.
acc_w: 5.6386016813618435e-03      # accelerometer bias random work noise standard deviation.
gyr_w: 6.996094830870257e-04       # gyroscope bias random work noise standard deviation.
g_norm: 9.81     # gravity magnitude


################### optimizer ###################
patch_size_X: 1
patch_size_Y: 1
field_type: "inv_time_surface" # "distance_field" or "inv_time_surface"
# field_type: "distance_field" # "distance_field" or "inv_time_surface"
polarity_prediction: 0 #bool
batch_size: 400
max_registration_point: 5000
use_batch_optimization: 1


################### GLOG ###################
log_dir: ""
log_color: 1
log_also_to_stderr: 1


################### Viewer ###################
point_size: 1
frame_size: 0.02
